name: "Ready for review"
on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review

jobs:
  ready-for-review:
    runs-on: ubuntu-latest
    steps:
      - uses: andymckay/labeler@1.0.4
        with:
          add-labels: "Ready for review"
