name: "Autolabel"
on:
  pull_request_target:
    types:
        - opened
        - reopened
        - ready_for_review
        - converted_to_draft
        - closed
  pull_request_review:
    types:
        - submitted
    
jobs:
  autolabel:
    runs-on: ubuntu-latest
    steps:
      - name: "Autolabel"
        uses: bswaidner/autolabel@master
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
