name: "Auto-Label"
on:
  pull_request_target:
    types:
        - closed

jobs:
  closed:
    name: "Closed"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ".github/workflows/autolabel/closed.yml"
        sync-labels: true
