name: "Auto-Label"
on:
  pull_request_target:
    types:
        - opened
        - reopened
        - ready_for_review
    

jobs:
  ready-for-review:
    name: "Ready for review"
    if: github.event.review.state != 'approved' && github.event.pull_request.merged == false && github.event.pull_request.draft == false && github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: ".github/workflows/autolabel/ready_for_review.yml"
        sync-labels: true
